version: 0.2

phases:
  install:
    commands:
      - echo "Installing SSH client"
      - yum install -y openssh-clients

  pre_build:
    commands:
      - echo "Fetching private key from Secrets Manager"
      - aws secretsmanager get-secret-value --secret-id ec2-ssh-key --query SecretString --output text > highend.pem
      - chmod 400 highend.pem

  build:
    commands:
      - echo "Copying website to EC2"
      - scp -o StrictHostKeyChecking=no -i highend.pem index.html ubuntu@15.152.152.13:/home/ubuntu/

      - echo "Deploying and restarting Nginx"
      - |
        ssh -o StrictHostKeyChecking=no -i highend.pem ubuntu@15.152.152.13 << EOF
          sudo cp /home/ubuntu/index.nginx-debian.html /var/www/html/index.nginx-debian.html
          sudo systemctl restart nginx
        EOF

artifacts:
  files:
    - '**/*'
