version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 860616632758.dkr.ecr.ap-northeast-3.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t app1-repo .
      - docker tag app1-repo:latest 860616632758.dkr.ecr.ap-northeast-3.amazonaws.com/app1-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push 860616632758.dkr.ecr.ap-northeast-3.amazonaws.com/app1-repo:latest

artifacts:
  files:
    - appspec.yml
    - deploy.sh
